console.log('NepaliFunctions.ConvertToDateObject("2000-01-01", "YYYY-MM-DD")');
console.log(NepaliFunctions.ConvertToDateObject("2000-01-01", "YYYY-MM-DD"));
console.log('NepaliFunctions.ConvertToDateObject("2000/01/01", "YYYY/MM/DD")');
console.log(NepaliFunctions.ConvertToDateObject("2000/01/01", "YYYY/MM/DD"));
console.log('NepaliFunctions.ConvertToDateObject("01-01-2000", "MM-DD-YYYY")');
console.log(NepaliFunctions.ConvertToDateObject("01-01-2000", "MM-DD-YYYY"));
console.log('NepaliFunctions.ConvertToDateObject("01/01/2000", "MM/DD/YYYY")');
console.log(NepaliFunctions.ConvertToDateObject("01/01/2000", "MM/DD/YYYY"));
console.log('NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY-MM-DD")');
console.log(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY-MM-DD"));
console.log('NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY/MM/DD")');
console.log(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY/MM/DD"));
console.log('NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM-DD-YYYY")');
console.log(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM-DD-YYYY"));
console.log('NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM/DD/YYYY")');
console.log(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM/DD/YYYY"));
console.log('NepaliFunctions.AD2BS({year: 2001, month: 6, day: 1})');
console.log(NepaliFunctions.AD2BS({year: 2001, month: 6, day: 1}));
console.log('NepaliFunctions.AD2BS({year: 2008, month: 5, day: 28})');
console.log(NepaliFunctions.AD2BS({year: 2008, month: 5, day: 28}));
console.log('NepaliFunctions.BS2AD({year: 2058, month: 2, day: 19})');
console.log(NepaliFunctions.BS2AD({year: 2058, month: 2, day: 19}));
console.log('NepaliFunctions.BS2AD({year: 2065, month: 2, day: 15})');
console.log(NepaliFunctions.BS2AD({year: 2065, month: 2, day: 15}));
console.log('NepaliFunctions.ValidateBsDate({year: 2000, month: 2, day: 30})');
console.log(NepaliFunctions.ValidateBsDate({year: 2000, month: 2, day: 30}));
console.log('NepaliFunctions.ValidateBsDate({year: 2064, month: 4, day: 32})');
console.log(NepaliFunctions.ValidateBsDate({year: 2064, month: 4, day: 32}));
console.log('NepaliFunctions.ValidateBsDate({year: 2000, month: 13, day: 30})');
console.log(NepaliFunctions.ValidateBsDate({year: 2000, month: 13, day: 30}));
console.log('NepaliFunctions.ValidateBsDate({year: 2000, month: 12, day: 32})');
console.log(NepaliFunctions.ValidateBsDate({year: 2000, month: 12, day: 32}));
console.log('NepaliFunctions.GetCurrentAdDate()');
console.log(NepaliFunctions.GetCurrentAdDate());
console.log('NepaliFunctions.GetCurrentAdYear()');
console.log(NepaliFunctions.GetCurrentAdYear());
console.log('NepaliFunctions.GetCurrentAdMonth()');
console.log(NepaliFunctions.GetCurrentAdMonth());
console.log('NepaliFunctions.GetCurrentAdDay()');
console.log(NepaliFunctions.GetCurrentAdDay());
console.log('NepaliFunctions.GetCurrentBsDate()');
console.log(NepaliFunctions.GetCurrentBsDate());
console.log('NepaliFunctions.GetCurrentBsYear()');
console.log(NepaliFunctions.GetCurrentBsYear());
console.log('NepaliFunctions.GetCurrentBsMonth()');
console.log(NepaliFunctions.GetCurrentBsMonth());
console.log('NepaliFunctions.GetCurrentBsDay()');
console.log(NepaliFunctions.GetCurrentBsDay());
console.log('NepaliFunctions.GetAdMonths()');
console.log(NepaliFunctions.GetAdMonths());
console.log('NepaliFunctions.GetAdMonth(0)');
console.log(NepaliFunctions.GetAdMonth(0));
console.log('NepaliFunctions.GetAdMonth(5)');
console.log(NepaliFunctions.GetAdMonth(5));
console.log('NepaliFunctions.GetAdMonth(11)');
console.log(NepaliFunctions.GetAdMonth(11));
console.log('NepaliFunctions.GetAdMonth(-1)');
console.log(NepaliFunctions.GetAdMonth(-1));
console.log('NepaliFunctions.GetAdMonth(12)');
console.log(NepaliFunctions.GetAdMonth(12));
console.log('NepaliFunctions.GetBsMonths()');
console.log(NepaliFunctions.GetBsMonths());
console.log('NepaliFunctions.GetBsMonth(0)');
console.log(NepaliFunctions.GetBsMonth(0));
console.log('NepaliFunctions.GetBsMonth(5)');
console.log(NepaliFunctions.GetBsMonth(5));
console.log('NepaliFunctions.GetBsMonth(11)');
console.log(NepaliFunctions.GetBsMonth(11));
console.log('NepaliFunctions.GetBsMonth(-1)');
console.log(NepaliFunctions.GetBsMonth(-1));
console.log('NepaliFunctions.GetBsMonth(12)');
console.log(NepaliFunctions.GetBsMonth(12));
console.log('NepaliFunctions.GetBsMonthsInUnicode()');
console.log(NepaliFunctions.GetBsMonthsInUnicode());
console.log('NepaliFunctions.GetBsMonthInUnicode(0)');
console.log(NepaliFunctions.GetBsMonthInUnicode(0));
console.log('NepaliFunctions.GetBsMonthInUnicode(5)');
console.log(NepaliFunctions.GetBsMonthInUnicode(5));
console.log('NepaliFunctions.GetBsMonthInUnicode(11)');
console.log(NepaliFunctions.GetBsMonthInUnicode(11));
console.log('NepaliFunctions.GetBsMonthInUnicode(-1)');
console.log(NepaliFunctions.GetBsMonthInUnicode(-1));
console.log('NepaliFunctions.GetBsMonthInUnicode(12)');
console.log(NepaliFunctions.GetBsMonthInUnicode(12));
console.log('NepaliFunctions.GetBsDaysUnicode()');
console.log(NepaliFunctions.GetBsDaysUnicode());
console.log('NepaliFunctions.GetBsDayUnicode(0)');
console.log(NepaliFunctions.GetBsDayUnicode(0));
console.log('NepaliFunctions.GetBsDayUnicode(4)');
console.log(NepaliFunctions.GetBsDayUnicode(4));
console.log('NepaliFunctions.GetBsDayUnicode(7)');
console.log(NepaliFunctions.GetBsDayUnicode(7));
console.log('NepaliFunctions.GetBsDaysUnicodeShort()');
console.log(NepaliFunctions.GetBsDaysUnicodeShort());
console.log('NepaliFunctions.GetAdDays()');
console.log(NepaliFunctions.GetAdDays());
console.log('NepaliFunctions.GetAdDay(0)');
console.log(NepaliFunctions.GetAdDay(0));
console.log('NepaliFunctions.GetAdDay(5)');
console.log(NepaliFunctions.GetAdDay(5));
console.log('NepaliFunctions.GetAdDay(7)');
console.log(NepaliFunctions.GetAdDay(7));
console.log('NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, false)');
console.log(NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, false));
console.log('NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, false)');
console.log(NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, false));
console.log('NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, true)');
console.log(NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, true));
console.log('NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, true)');
console.log(NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, true));
console.log('NepaliFunctions.GetAdFullDate({year: 2001, month: 3, day: 15})');
console.log(NepaliFunctions.GetAdFullDate({year: 2001, month: 3, day: 15}));
console.log('NepaliFunctions.GetAdFullDate({year: 2003, month: 5, day: 2})');
console.log(NepaliFunctions.GetAdFullDate({year: 2003, month: 5, day: 2}));
console.log('NepaliFunctions.GetAdFullDay({year: 2001, month: 3, day: 15})');
console.log(NepaliFunctions.GetAdFullDay({year: 2001, month: 3, day: 15}));
console.log('NepaliFunctions.GetAdFullDay({year: 2003, month: 5, day: 2})');
console.log(NepaliFunctions.GetAdFullDay({year: 2003, month: 5, day: 2}));
console.log('NepaliFunctions.BsAddDays({year: 2001, month: 3, day: 15}, 2)');
console.log(NepaliFunctions.BsAddDays({year: 2001, month: 3, day: 15}, 2));
console.log('NepaliFunctions.BsAddDays({year: 2003, month: 5, day: 2}, 90)');
console.log(NepaliFunctions.BsAddDays({year: 2003, month: 5, day: 2}, 90));
console.log('NepaliFunctions.AdDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17})');
console.log(NepaliFunctions.AdDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17}));
console.log('NepaliFunctions.AdDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1})');
console.log(NepaliFunctions.AdDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1}));
console.log('NepaliFunctions.BsDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17})');
console.log(NepaliFunctions.BsDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17}));
console.log('NepaliFunctions.BsDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1})');
console.log(NepaliFunctions.BsDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1}));
console.log('NepaliFunctions.GetDaysInAdMonth(2015, 2)');
console.log(NepaliFunctions.GetDaysInAdMonth(2015, 2));
console.log('NepaliFunctions.GetDaysInAdMonth(2020, 1)');
console.log(NepaliFunctions.GetDaysInAdMonth(2020, 1));
console.log('NepaliFunctions.GetDaysInBsMonth(2015, 2)');
console.log(NepaliFunctions.GetDaysInBsMonth(2015, 2));
console.log('NepaliFunctions.GetDaysInBsMonth(2020, 1)');
console.log(NepaliFunctions.GetDaysInBsMonth(2020, 1));
console.log('NepaliFunctions.ConvertToUnicode(123456789)');
console.log(NepaliFunctions.ConvertToUnicode(123456789));
console.log('NepaliFunctions.ConvertToUnicode(123.50)');
console.log(NepaliFunctions.ConvertToUnicode(123.50));
console.log('NepaliFunctions.ConvertToNumber("१२३४५६७८९")');
console.log(NepaliFunctions.ConvertToNumber("१२३४५६७८९"));
console.log('NepaliFunctions.ConvertToNumber("१२३.५")');
console.log(NepaliFunctions.ConvertToNumber("१२३.५"));
console.log('NepaliFunctions.Get2DigitNo(1)');
console.log(NepaliFunctions.Get2DigitNo(1));
console.log('NepaliFunctions.Get2DigitNo(12)');
console.log(NepaliFunctions.Get2DigitNo(12));
console.log('NepaliFunctions.NumberToWords(123456000.12)');
console.log(NepaliFunctions.NumberToWords(123456000.12));
console.log('NepaliFunctions.NumberToWords(12)');
console.log(NepaliFunctions.NumberToWords(12));
console.log('NepaliFunctions.NumberToWordsUnicode(123456000.12)');
console.log(NepaliFunctions.NumberToWordsUnicode(123456000.12));
console.log('NepaliFunctions.NumberToWordsUnicode(12)');
console.log(NepaliFunctions.NumberToWordsUnicode(12));